export enum ApprovalType {
  WORK_PROGRAM = "WORK_PROGRAM",
  EVENT = "EVENT",
  FINANCE = "FINANCE",
  DOCUMENT = "DOCUMENT",
  DOCUMENT_PROPOSAL = "DOCUMENT_PROPOSAL",
  DOCUMENT_ACCOUNTABILITY_REPORT = "DOCUMENT_ACCOUNTABILITY_REPORT",
  LETTER = "LETTER",
}

export enum StatusApproval {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}
