export enum UserRole {
  DPO = "DPO",
  BPH = "BPH",
  PENGURUS = "PENGURUS",
  ANGGOTA = "ANGGOTA",
}

export enum Department {
  INFOKOM = "INFOKOM",
  PSDM = "PSDM",
  LITBANG = "LITBANG",
  KWU = "KWU",
}

export enum Position {
  KETUA_UMUM = "KETUA_UMUM",
  WAKIL_KETUA_UMUM = "WAKIL_KETUA_UMUM",
  SEKRETARIS = "SEKRETARIS",
  BENDAHARA = "BENDAHARA",
  KEPALA_DEPARTEMEN = "KEPALA_DEPARTEMEN",
  STAFF_DEPARTEMEN = "STAFF_DEPARTEMEN",
}

export enum PeriodStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
  ALL = "all",
}

export enum FinanceType {
  INCOME = "INCOME",
  EXPENSE = "EXPENSE"
}

export enum DocumentType {
  PROPOSAL = "PROPOSAL",
  LPJ = "LPJ",
  BUDGET_PLAN = "BUDGET_PLAN",
  TIMELINE = "TIMELINE",
  WORKPLAN = "WORKPLAN",
  FINANCIAL_REPORT = "FINANCIAL_REPORT",
  ATTENDANCE_LIST = "ATTENDANCE_LIST",
  ACTIVITY_REPORT = "ACTIVITY_REPORT",
  EVALUATION_REPORT = "EVALUATION_REPORT",
  INVOICE = "INVOICE",
  RECEIPT = "RECEIPT",
  OFFICIAL_LETTER = "OFFICIAL_LETTER",
  MEMORANDUM = "MEMORANDUM",
  POSTER = "POSTER",
  BROCHURE = "BROCHURE",
  PRESENTATION = "PRESENTATION",
  CERTIFICATE = "CERTIFICATE",
  DECREE = "DECREE",
  OTHER = "OTHER"
}

// Enum Status untuk berbagai entitas
export enum Status {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REVISION = "REVISION",
  ARCHIVED = "ARCHIVED",
  ONGOING = "ONGOING",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  POSTPONED = "POSTPONED"
}

// Enum Letter Type
export enum LetterType {
  OUTGOING = "OUTGOING",
  INCOMING = "INCOMING"
}

// Enum Letter Priority
export enum LetterPriority {
  NORMAL = "NORMAL",
  IMPORTANT = "IMPORTANT",
  URGENT = "URGENT"
}

export enum ApprovalType {
  WORK_PROGRAM = "WORK_PROGRAM",
  EVENT = "EVENT",
  FINANCE = "FINANCE",
  DOCUMENT = "DOCUMENT",
  ARTICLE = "ARTICLE",
  LETTER = "LETTER",
  SHORT_LINK = "SHORT_LINK",
  LINK_HUB = "LINK_HUB",
  LINK_HUB_DETAIL = "LINK_HUB_DETAIL",
  LINK_HUB_THEME = "LINK_HUB_THEME",
  ORGANIZATIONAL_STRUCTURE = "ORGANIZATIONAL_STRUCTURE",
  DEPARTMENT_TASK = "DEPARTMENT_TASK"
}

export enum ApiResponseStatus {
  SUCCESS = "success",
  ERROR = "error",
}