import {
  Loader2,
  Mail,
  Check,
  ChevronDown,
  Calendar,
  X,
  ArrowRight,
  Search,
  Activity,
  Users,
  FileText,
  CalendarDays,
  DollarSign,
  FileCheck,
  Newspaper,
  Image,
  Briefcase,
  TrendingUp,
  Clock,
  AlertCircle,
  CheckCircle,
  User,
  // Tambahkan icon lain yang dibutuhkan
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  check: Check,
  chevronDown: ChevronDown,
  calendar: Calendar,
  close: X,
  arrowRight: ArrowRight,
  search: Search,
  activity: Activity,
  users: Users,
  fileText: FileText,
  calendarDays: CalendarDays,
  dollarSign: DollarSign,
  fileCheck: FileCheck,
  newspaper: Newspaper,
  image: Image,
  briefcase: Briefcase,
  trendingUp: TrendingUp,
  clock: Clock,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  user: User,
  // Tambahkan mapping icon lainnya di sini
};
